#!/usr/bin/env bash
# 构建：按 manifest 顺序拼接源模块 → 单一可部署 main.java。
# 用法: ./build.sh [manifest] [out]
set -eu
cd "$(dirname "$0")"
MANIFEST="${1:-build/manifest.prod.txt}"
OUT="${2:-out/main.java}"
mkdir -p "$(dirname "$OUT")"

{
  echo "// ============================================================"
  echo "// AUTO-GENERATED by merged/build.sh — DO NOT EDIT THIS FILE."
  echo "// 源在 merged/src/，按 $MANIFEST 顺序拼接。改逻辑改源模块后重跑 build.sh。"
  echo "// ============================================================"
  while IFS= read -r f; do
    case "$f" in ''|\#*) continue ;; esac
    if [ ! -f "$f" ]; then echo "build.sh: missing module $f" >&2; exit 1; fi
    echo ""
    echo "// ===== module: $f ====="
    cat "$f"
  done < "$MANIFEST"
} > "$OUT"

echo "built $OUT ($(wc -l < "$OUT" | tr -d ' ') lines) from $MANIFEST"
